import '../styles/globals.css'
import Layout from '../components/Layout'
import Head from 'next/head'
import Script from 'next/script'

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Create Next App</title>
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous"
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous" />
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="/plugins/bootstrap/bootstrap.min.css" />

      <link rel="stylesheet" href="/plugins/animate-css/animate.css" />

      <link rel="stylesheet" href="/plugins/fontawesome/css/all.css" />
      <link rel="stylesheet" href="/plugins/fonts/Pe-icon-7-stroke.css" />

      <link rel="stylesheet" href="/plugins/themify/css/themify-icons.css" />

      <link rel="stylesheet" href="/plugins/slick-carousel/slick/slick.css" />
      <link rel="stylesheet" href="/plugins/slick-carousel/slick/slick-theme.css" />
      <link rel="stylesheet" href="/css/style.css"></link>

    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>



    <script src="/plugins/jquery/jquery.min.js" />

    <script src="/plugins/bootstrap/bootstrap.min.js" />

    <script src="./plugins/slick-carousel/slick/slick.min.js" />
    <script src="./js/script.js" />
  </>
}

export default MyApp
